services:
  php:
    build:
      context: .docker/php
    volumes:
      - ./:/var/www/api
    working_dir: /var/www/api
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/api
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:10.11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carwash
      MYSQL_USER: carwash
      MYSQL_PASSWORD: carwash
    ports:
      - "3306:3306"
    volumes:
      - .docker/db/data:/var/lib/mysql

volumes:
  db_data: